package pl.edu.agh.miss;

public enum ParticleType {
    Oxaloacetate,
    AcetylCoA,
    H2O,
    Citrate,
    CoASH,
    CisAconitate,
    Isocitrate,
    NADPlus,
    Oxalosuccinate,
    NADH,
    HPlus,
    AlphaKetoglutarate,
    CO2,
    SuccinylCoA,
    GDP,
    Pi,
    Succinate,
    GTP,
    Ubiquinone,
    Fumarate,
    Ubiquinol,
    LMalate,

    // Enzymes:
    CitrateSynthase,
    Aconitase,
    IsocitrateDehydrogenase,
    AlphaKetoglutarateDehydrogenase,
    SuccinylCoASynthetase,
    SuccinateDehydrogenase,
    Fumarase,
    MalateDehydrogenase,
}